name: Test react app - basic
on:
  workflow_dispatch:

jobs:

  start:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16, 18, 20, 21]
    name: test on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm ci

      - name: Start server
        run: npm start &

      - name: Test the website
        run: npx cypress run
